const fs = require('fs-extra');
const path = require('path');

async function generateEnvFile(projectPath, config) {
  const envContent = buildEnvContent(config);
  const envPath = path.join(projectPath, '.env');
  
  await fs.writeFile(envPath, envContent);
}

function buildEnvContent(config) {
  const lines = [
    '# Environment Configuration',
    '# Generated by create-enfyra-app',
    '',
    '# Application Settings',
    `NODE_ENV=development`,
    `PORT=${config.port}`,
    '',
    '# API Configuration',
    `API_URL=${config.apiUrl}`,
    `API_BASE_URL=${config.apiUrl}`,
    ''
  ];

  // Framework-specific environment variables
  if (config.framework === 'nuxt3') {
    lines.push(
      '# Nuxt Configuration',
      `NUXT_PORT=${config.port}`,
      `NUXT_HOST=localhost`,
      `NUXT_SSR=${config.renderMode === 'universal' ? 'true' : 'false'}`,
      ''
    );
  } else if (config.framework === 'vue3') {
    lines.push(
      '# Vue Configuration',
      `VITE_API_URL=${config.apiUrl}`,
      `VITE_APP_TITLE=${config.projectName}`,
      ''
    );
  } else if (config.framework === 'react-vite') {
    lines.push(
      '# React Configuration',
      `VITE_API_URL=${config.apiUrl}`,
      `VITE_APP_TITLE=${config.projectName}`,
      ''
    );
  }

  // Development settings
  lines.push(
    '# Development Settings',
    'DEBUG=false',
    'VERBOSE=false',
    '',
    '# Security (Change in production)',
    `JWT_SECRET=${generateRandomString(64)}`,
    `SESSION_SECRET=${generateRandomString(32)}`,
    '',
    '# Optional: Analytics & Monitoring',
    '# SENTRY_DSN=',
    '# GA_TRACKING_ID=',
    '',
    '# Optional: Email Configuration',
    '# SMTP_HOST=',
    '# SMTP_PORT=587',
    '# SMTP_USER=',
    '# SMTP_PASSWORD=',
    '',
    '# Optional: Storage Configuration',
    '# AWS_ACCESS_KEY_ID=',
    '# AWS_SECRET_ACCESS_KEY=',
    '# AWS_REGION=us-east-1',
    '# AWS_S3_BUCKET=',
    ''
  );

  return lines.join('\n');
}

function generateRandomString(length) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=';
  let result = '';
  
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  
  return result;
}

module.exports = {
  generateEnvFile
};